services:
  mongodb:
    image: mongo:7
    container_name: crimen-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
